<?php

namespace Tests\Unit\Http\Controllers;

use App\Http\Controllers\BookController;
use App\Models\Book;
use PHPUnit\Framework\TestCase;

class BookControllerTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->controller = new BookController();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testBooks()
    {
        $book = Book::all();
        //$result = $this->controller->books($book);
        $item = $result->last();
        $this->assertTrue(true);
    }
}
